### ISSUE TITLE
DocumentBinder not found in laravel 8

### ISSUE THREAD

**Issue by waqas61** [PhpGt/DomTemplate#279]
Try to initiate  DocumentBinder to bind values but its giving error : "Class 'Gt\\DomTemplate\\DocumentBinder' not found"

`use Gt\DomTemplate\HTMLDocument;`
`use Gt\DomTemplate\DocumentBinder;`

`$html = '<span class="name-output">Set value</span>';`
`$document = new HTMLDocument($html);`
` $span = $document->querySelector(".name-output");`
`$binder = new \Gt\DomTemplate\DocumentBinder($document);`

**Comment by g105b** [comment]
Hi @waqas61,

Have you had chance to check this over? Happy to assist with your implementation wherever I can.

Greg.
