### ISSUE TITLE
Feedback on wiki Binding page

### ISSUE THREAD

**Issue by j4m3s** [PhpGt/DomTemplate#414]
* I would include the simplest possible code for constructing the HtmlDocument and Binder in the example.  The first thing I look for is a working example to see how it all hangs together - and what's here doesn't work without me hunting round other pages.  Include those extra few lines from https://github.com/PhpGt/DomTemplate/blob/master/examples/binding/01-simple.php.
  * In reading the simplest example I was immediately concerned that I can only replace everything with a single bound value.  It's dead simple, but totally unrealistic.  I'd go so far as to say that having the functionality in DomTemplate to *not* specify a key is counterintuitive, and could be quite unhelpful...  Even if you choose to leave it in, I'd definitely specify the key in this example.  Also, what's happened to the ini block at the top of the previous example?
  * more complex example section:
	  * Move the "Our example function is being passed a..." to after the HTML section.  Maybe even after the PHP.  With it where it is I looked at the html and wondered where it was being passed.
	  * Use an associative array in the example and bind to that, not a data-source where we can't tell what it returns (and isn't part of DomTemplate anyway).  It would be clearer. You can make a reference to the fact the array could the product of a database call etc.
	  * I don't understand the `$binder->bindKeyValue("year", $currentYear);` bit.  Why?  What does that do?
	  * what's data-template?
	  * what's with the double-curly braces?  I don't know where countryCode comes from.
  * Null values and empty strings section
    * "With this knowledge, you can provide default values within the HTML and further reduce the logic required in PHP to manipulate the data to the desired shape."  Hmm, now you're confusing the concerns of the different tiers.  If presentation is purely for presentation (and it should be), it shouldn't contain defaults.  The php should inject the correct data either way.
    * On which note, I just don't get the rebind thing.  Does the example you give mean that we've written our html in such a way as to have some `data-bind:text='id'` items specifying order IDs and others specifying user IDs, reusing the same attribute?  
    * I think the "null values and empty strings" section and the "Rebinding with data-rebind" sections should move to lower in the doc, they're out of place there.  At the moment, the idea of rebinding is a bit odd - so far you've only talked about "the element is having its textContent set to the string "Cody"" for example, no talk of binding.
  * The data-bind attribute section
    * "followed by the bind property - what HTMLElement property to bind to".  "HTMLElement property" needs more explanation.  Isn't text called textContent in HTML?
    * As above, I think bind key should be mandatory otherwise apparently random stuff will happen for noobs like me.  On which note, do you have some sort of validator as part of the framework, or a log-level that I can set as a user to flag when I've got a data-bind attribute that's not been injected, or a `bindValue` call that's failed to bind?  How do I know when my loosly coupled tiers are out-of-sync?
  * Bind Properties section
    * Bingo, I've reached the explanation for one of my questions above re bind properties.  You might want to make the bit above (followed by the bind property - what HTMLElement property to bind to) a link to this section, or have this bit a concertina that opens under that bit above.
    * "when you want to toggle the class attribute." - I think you mean toggle some of the values inside the class attribute, not the attribute itself?
    * Interesting, you've now pointed-out that text is a synonym for textContent, addressing one of my questions above.  I'd use textContent in the examples, it's less confusing.
    * "<input name="user" data-bind:value="username" required /> - the bind property is value, and the bind key is specified as username." doesn't tell me anything new.  I think you're saying that "the data bound to the username bind key in your PHP will be used to add and set a `value` attribute to the input". 
    * Same with the next example.  You're telling us what's written in the html example rather than what will happen when we bind to the key :)
    * " More about bind modifiers later in this section."  I think it's a separate page now, not later in this section?
  * Bind Keys
    * " it's possible to pass a key-value-pair data structure to the bindData function," rather than having bindData function as a link I'd just say there's more info below.  Elsewhere in the wiki, I think you've followed a convention where a link is used to open a separate page?
  * Bind functions
    * "With all bind functions, the last parameter is an optional Element called $context, which defines the scope of where the binding will occur. Passing an Element object will only bind elements within the tree of that Element. Leave the parameter unset to have the scope set to the whole Document." is a repeat of what you said already above the bullet-list.
    * Hmm I'm left wondering why `data-template` is used with bindList.  Wouldn't `data-list-item` be more intuitive?  Or should the method be called `bindTemplatedList`?

**Comment by g105b** [comment]
To help me digest your feedback and action it into documentation I'm splitting out my thoughts here.

> I would include the simplest possible code for constructing the HtmlDocument and Binder in the example. The first thing I look for is a working example to see how it all hangs together - and what's here doesn't work without me hunting round other pages. Include those extra few lines from https://github.com/PhpGt/DomTemplate/blob/master/examples/binding/01-simple.php.

- [ ] Document how to run the examples, and why `example()` is used (webengine's `go()` function)

>     In reading the simplest example I was immediately concerned that I can only replace everything with a single bound value. It's dead simple, but totally unrealistic. I'd go so far as to say that having the functionality in DomTemplate to not specify a key is counterintuitive, and could be quite unhelpful... Even if you choose to leave it in, I'd definitely specify the key in this example. Also, what's happened to the ini block at the top of the previous example?

- [ ] List out the different bind functions earlier, and explain why each one exists

>     more complex example section:
>         Move the "Our example function is being passed a..." to after the HTML section. Maybe even after the PHP. With it where it is I looked at the html and wondered where it was being passed.

- [ ] Re-order example code in this section.

>         Use an associative array in the example and bind to that, not a data-source where we can't tell what it returns (and isn't part of DomTemplate anyway). It would be clearer. You can make a reference to the fact the array could the product of a database call etc.

- [ ] Add explanation to the docs for where the data source comes from. Provide assoc-array alternative, explaining that the binder works with not just assoc-arrays.

>         I don't understand the $binder->bindKeyValue("year", $currentYear); bit. Why? What does that do?

- [ ] Give an explanation to why this is the case (year is used as the input to the database and is not part of the response)

>         what's data-template?

- [ ] Give a brief explanation of data-template / data-list-item before we get to that part.

>         what's with the double-curly braces? I don't know where countryCode comes from.

- [ ] Give a brief explanation of double-curlies.
- [ ] Make sure there's an Interface shown or something similar for the `Driver` object, or describe the ArrayShape if switching to assoc-array.

>     Null values and empty strings section
>         "With this knowledge, you can provide default values within the HTML and further reduce the logic required in PHP to manipulate the data to the desired shape." Hmm, now you're confusing the concerns of the different tiers. If presentation is purely for presentation (and it should be), it shouldn't contain defaults. The php should inject the correct data either way.

I need to give this some thought. I find it super useful to have default values in the HTML, and I wonder whether this should be communicated differently in the docs.

>         On which note, I just don't get the rebind thing. Does the example you give mean that we've written our html in such a way as to have some data-bind:text='id' items specifying order IDs and others specifying user IDs, reusing the same attribute?

- [ ] Clarify rebinding `id`. It makes sense to me, but it's obviously confusingly written.

>         I think the "null values and empty strings" section and the "Rebinding with data-rebind" sections should move to lower in the doc, they're out of place there. At the moment, the idea of rebinding is a bit odd - so far you've only talked about "the element is having its textContent set to the string "Cody"" for example, no talk of binding.

- [ ] Move rebind and null values lower in the doc.

>     The data-bind attribute section
>         "followed by the bind property - what HTMLElement property to bind to". "HTMLElement property" needs more explanation. Isn't text called textContent in HTML?

- [ ] Explain why we can't use `textContent` as the data bind property.

>         As above, I think bind key should be mandatory otherwise apparently random stuff will happen for noobs like me. On which note, do you have some sort of validator as part of the framework, or a log-level that I can set as a user to flag when I've got a data-bind attribute that's not been injected, or a bindValue call that's failed to bind? How do I know when my loosly coupled tiers are out-of-sync?

- [ ] Create an issue to log this debug functionality.

>     Bind Properties section
>         Bingo, I've reached the explanation for one of my questions above re bind properties. You might want to make the bit above (followed by the bind property - what HTMLElement property to bind to) a link to this section, or have this bit a concertina that opens under that bit above.

- [ ] Link "what HTMLElement property to bind to" to Bind Properties section

>         "when you want to toggle the class attribute." - I think you mean toggle some of the values inside the class attribute, not the attribute itself?

- [ ] Reword class toggling.

>         Interesting, you've now pointed-out that text is a synonym for textContent, addressing one of my questions above. I'd use textContent in the examples, it's less confusing.
>         " - the bind property is value, and the bind key is specified as username." doesn't tell me anything new. I think you're saying that "the data bound to the username bind key in your PHP will be used to add and set a value attribute to the input".
>         Same with the next example. You're telling us what's written in the html example rather than what will happen when we bind to the key :)

- [ ] Add clarification to this section that the purpose of listing out the examples is to help understand the terminology of "property", "key", etc.

>         " More about bind modifiers later in this section." I think it's a separate page now, not later in this section?

- [ ] Link to bind modifiers instead of "More about bind modifiers later in this section".

>     Bind Keys
>         " it's possible to pass a key-value-pair data structure to the bindData function," rather than having bindData function as a link I'd just say there's more info below. Elsewhere in the wiki, I think you've followed a convention where a link is used to open a separate page?
>     Bind functions
>         "With all bind functions, the last parameter is an optional Element called $context, which defines the scope of where the binding will occur. Passing an Element object will only bind elements within the tree of that Element. Leave the parameter unset to have the scope set to the whole Document." is a repeat of what you said already above the bullet-list.
>         Hmm I'm left wondering why data-template is used with bindList. Wouldn't data-list-item be more intuitive? Or should the method be called bindTemplatedList?
> 

data-template has just been what it's always been called and I've never questioned it. You're completely right though. `data-list-item` makes a lot more sense, and doesn't have to break anything... we can use both, but only document one.

- [ ] Document `data-template` as `data-list-item` (after introducing this in code and tests)

**Comment by g105b** [comment]
- How to run code examples (new overview section) https://github.com/PhpGt/DomTemplate/wiki/overview#code-examples-in-this-guide
- `data-template` is now synonymous with `data-list`, which makes loads more sense as a naming convention, because we interact with lists via the `bindList()` function

**Comment by g105b** [comment]
I've removed this section from the first bind page, as I feel like it goes too hard on the specific examples before anything's explained:

```
## Simple example

### Simplest possible usage

Source HTML:

```html
<h1 data-bind:text>Name</h1>
```

PHP:

```php
function example(DocumentBinder $binder):void {
	$binder->bindValue("Cody");
}
```

Output HTML:

```html
<h1>Cody</h1>
```

What's happening in this example is the `<h1>` element is having its `textContent` set to the string `"Cody"`. If the `bindValue()` function isn't called, the `textContent` of the element remains as its default value (in this case, `"Name"`). This allows default values to be set in the HTML source, requiring no PHP execution, and makes it easy to add dynamic behaviour that only executes when a button is clicked, for example. 

<details>
<summary>Jump straight into a more complex example.</summary>

### Non-trivial usage

In this example, we see a page output information about [Formula 1](https://en.wikipedia.org/wiki/Formula_One) racing drivers.

Our example function is being passed a `DriverRepository` object that represents our application's data source. We don't need to know anything about the data source's implementation, only that its `getDrivers` function can be called to retrieve an array of `Driver` objects. The implementation of a `Driver` object will provide the bindable values where appropriate.

Source HTML:

```html
<h1>Top three drivers of <span data-bind:text="year">0000</span></h1>

<ul>
	<li data-list>
		<h2 data-bind:text="name">Name of driver</h2>
		<h3 data-bind:text="team">Team Name</h3>

		<p>Points: <span data-bind:text="points">0</span>
		<div>
			<img src="/flag/{{countryCode}}.png" alt="Flag of {{countryName}}" />
			<p data-bind:text="countryName">Country</p>
		</div>
	</li>
</ul>
```

PHP:

```php
function example(DocumentBinder $binder, DriverRepository $driverRepo):void {
	$now = new DateTime();
	$currentYear = $now->format("Y");

	// Here we're calling an example data source to get an array of Driver objects.
	$drivers = $driverRepo->getDrivers(
		year: $currentYear,
		orderBy: "points", 
		limit: 3,
	);

	$binder->bindKeyValue("year", $currentYear);
	$binder->bindList($drivers);
}
```

Output HTML:

```html
<h1>Top three drivers of <span>2020</span></h1>

<ul>
	<li>
		<h2>Lewis Hamilton</h2>
		<h3>Mercedes</h3>

		<p>Points: <span>347</span>
		<div>
			<img src="/flag/GBR.png" alt="Flag of United Kingdom" />
			<p>United Kingdom</p>
		</div>
	</li>
	<li>
		<h2>Valtteri Bottas</h2>
		<h3>Mercedes</h3>

		<p>Points: <span>223</span>
		<div>
			<img src="/flag/FIN.png" alt="Flag of Finland" />
			<p>Finland</p>
		</div>
	</li>
	<li>
		<h2>Max Verstappen</h2>
		<h3>Red Bull Racing Honda</h3>

		<p>Points: <span>214</span>
		<div>
			<img src="/flag/NED.png" alt="Flag of Netherlands" />
			<p>Netherlands</p>
		</div>
	</li>
</ul>
```

See more [advanced examples](#bind-functions) at the end of this section.

</details>


### Null values and empty strings

Binding a `null` has different behaviour to binding an empty string `""`. Binding an empty string will set the bind property to an empty string, but binding `null` will leave the HTML unaffected. With this knowledge, you can provide default values within the HTML and further reduce the logic required in PHP to manipulate the data to the desired shape.

### Rebinding with `data-rebind`

Once an element's property has been bound once, its value will not change again with subsequent binds unless the element has a `data-rebind` attribute. This feature allows for a style of programming where specific areas of the document can be bound first, before applying a document-wide bind. 

For example, on an "Order summary" page of an e-commerce site, a list of orders can be bound to a specific element of the page. Each `Order` might have common bind keys such as `id`, `name`, etc. After binding this list to a specific element, a `User` object can be bound to the entire document, and any unbound `id`, `name` keys on the page will take that of the User. This is just an example of one style of programming that can help save a lot of time implementing common page layouts.
```

**Comment by g105b** [comment]
Thanks again @j4m3s for the feedback, I've actioned everything back into the docs now, hopefully this will improve the readability for everyone.
